services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  vsm:
    image: kr0nus/vsm:v2.0
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    depends_on:
      redis:
        condition: service_started
    volumes:
      - config:/app/config:ro

volumes:
  config:
    external: true