services:  
  vault:
    image: hashicorp/vault:latest
    restart: always
    expose:
      - 8200
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=admin
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    restart: always
    expose:
      - 8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
