services:  
  vault:
    image: hashicorp/vault:latest
    restart: always
    expose:
      - 8200
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=admin
  
  keycloak:
    image: bitnami/keycloak:latest
    restart: always
    expose:
      - 8080
    environment:
      - KEYCLOAK_HOSTNAME=kc.local.kronus.network
      - KEYCLOAK_PROXY_HEADERS=xforwarded
      - KEYCLOAK_DATABASE_VENDOR=dev-file 
      - KEYCLOAK_LOG_LEVEL=debug
      - KEYCLOAK_ROOT_LOG_LEVEL=DEBUG

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
  
  vsm:
    image: kr0nus/vsm:devel
    restart: always
    expose:
      - 3000
    depends_on:
      redis:
        condition: service_started
      keycloak:
        condition: service_started
      vault:
        condition: service_started
    volumes:
      - ./config/vsm:/app/config/vsm:ro
 
  haproxy:
    image: haproxy:latest
    restart: always
    ports: 
      - '80:80'
      - '443:443'
    networks:
      default:
        aliases:
          - vsm.local.kronus.network
          - hcv.local.kronus.network
          - kc.local.kronus.network
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy:ro
      - ./config/customca/leaf:/certs/
